---
Resources:
    MyEC2Instance: 
      Type: AWS::EC2::Instance
      Properties: 
       AvailabilityZone: ap-northeast-1c
       ImageId: ami-0de5311b2a443fb89
       InstanceType: t2.micro
       SubnetId: subnet-0a9431bfc5be0ecc0
       KeyName: mumbai1

