---
Resources:
  InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
       GroupDescription: Allow http to client host
       VpcId: vpc-0c6b872f8e919f2db
       SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/16
       SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/16